### ISSUE TITLE
FileNotFoundError on MacOS 10.13.3

### ISSUE THREAD

**Issue by mbusch-regis** [willsALMANJ/xontrib-autojump#1]
brew installed autojump

copied your autojump.xsh and autojump-completion.bash to ~/.config/autojump

Made suggested edit to .xonshrc and sourced.

Output:

PendingDeprecationWarning: FORMATTER_DICT is an alias of PROMPT_FIELDS and will be removed in the next release
prompt: error: on field 'update_autojump'
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
FileNotFoundError: [Errno 2] No such file or directory: 'autojump'

===========

Setting $XONSH-SHOW-TRACEBACK = True gives:

prompt: error: on field 'update_autojump'
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/Users/mbusch/anaconda3/lib/python3.6/site-packages/xonsh/prompt/__amalgam__.py", line 695, in _get_field_value
    value = field_value() if callable(field_value) else field_value
  File "/Users/mbusch/.config/autojump/autojump.xsh", line 33, in autojump_add_to_database
    stderr=f, stdout=DEVNULL)
  File "/Users/mbusch/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/mbusch/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/mbusch/anaconda3/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'autojump'

Line 33 is the subprocess call to autojump, which makes me think I need to add something to my path but I can't find exactly the right path to include to make the magic happen.

**Comment by mbusch-regis** [comment]
If I try putting an absolute path in the call statement, I get:

Please source the correct autojump file in your shell's
startup file. For more information, please reinstall autojump
and read the post installation instructions.

**Comment by mbusch-regis** [comment]
Apparently in xonsh, as far as os.getenv() is concerned, there is a difference between $AUTOJUMP_SOURCED and AUTOJUMP_SOURCED.

I added a line to your .xonshrc addition that fixes the problem:

import os
$AUTOJUMP_DIR = os.path.join($HOME, '.config/autojump')
print($AUTOJUMP_DIR)
source @(os.path.join($AUTOJUMP_DIR, 'autojump.xsh'))
os.putenv('AUTOJUMP_SOURCED', '1')

**Comment by wshanks** [comment]
Interesting. I haven't had time to play with xonsh much recently. I would like to get back to it. I assume this would affect me as well. `os.putenv('AUTOJUMP_SOURCED', '1')` should be added to `autojump.xsh` (in place of `$AUTOJUMP_SOURCED = 1`?) so the addition to .xonshrc doesn't have to grow.

**Comment by wshanks** [comment]
I think this has been fixed (this repo got forked and superseded and is being revived now with the code from the forked repo).
