### ISSUE TITLE
Simple releasing the PyPi package using Gihub Actions

### ISSUE THREAD

**Issue by anki-code** [willsALMANJ/xontrib-autojump#5]
Hi! Just want to let you know that there is very easy way to release the PyPi package of xontrib using Github Actions:

1. Click Actions 

![Screenshot_20200916_115026](https://user-images.githubusercontent.com/1708680/93314706-d2535d80-f812-11ea-8ff1-0a68bed2fd24.png)

2. Click Set up workflow on Publish Python Action

![Screenshot_20200916_114928](https://user-images.githubusercontent.com/1708680/93314630-b51e8f00-f812-11ea-9658-72dce0b2df06.png)

3. Commit the config without any changes

4. Go to repo Settings - Secrets and add:

![Screenshot_20200916_115332](https://user-images.githubusercontent.com/1708680/93315073-41c94d00-f813-11ea-99c1-be45daec0bec.png)

5. Now when you create Release and the Actions will publish the package to PyPi automatically (look at Actions link)

Enjoy :)

**Comment by wshanks** [comment]
Thanks, @anki-code! I never heard back from Sagar after https://github.com/xonsh/xonsh/issues/3725. Any suggestions for how to publish to PyPI? xontrib-autojump2? xontrib-autojump-ng? Or try going through the PyPI [name transfer process](https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer)?

I am not planning on disappearing but should I make someone else from the xonsh team an owner on PyPI as well to hedge against dealing with the same problem in the future?

**Comment by anki-code** [comment]
Hi!

> Or try going through the PyPI name transfer process?

Start from this way. I have an experience to transfer the names on Github and it works.

> to hedge against dealing with the same problem in the future?

Good question and it's actual for any repository and package :) Just keep the notifications on I think.

**Comment by wshanks** [comment]
I opened https://github.com/pypa/pypi-support/issues/854 a while ago and so far haven't heard anything. Looking through the other issues in the pypi-support repo, almost every PEP 541 request that is closed is closed with either "I gave up and chose a different name" or "I was able to contact the owner and get the project transferred".

Maybe we should just rename this xontrib? `xontrib-j`? `xontrib-autojump-alias`? It is tricky because adding anything onto `autojump` like `xontrib-autojump-new` sounds like a xontrib for a fork of autojump.

**Comment by anki-code** [comment]
Yeah, this will work.

Personally I moved from autojump to [zoxide](https://github.com/ajeetdsouza/zoxide) - it has more stable and modern support. Here is my script - https://github.com/ajeetdsouza/zoxide/issues/117#issuecomment-803782220

**Comment by wshanks** [comment]
Thanks, I did notice that the autojump directory has had very little activity in the last few years. I will give zoxide a try. That said, autojump does "just work" for me.

**Comment by wshanks** [comment]
https://github.com/pypa/pypi-support/issues/854 was finally resolved and then I finally had time to set this up.
